# Generated by Django 3.0.3 on 2020-11-25 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.forms.widgets
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juttu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juttunumero', models.CharField(default='', max_length=512)),
                ('case_nimi', models.CharField(blank=True, max_length=512, null=True)),
                ('nimike', models.CharField(default='', max_length=512)),
                ('tutkija', models.CharField(default='', max_length=512)),
                ('kiireellisyys', models.CharField(choices=[('Kiireellinen', 'Kiireellinen'), ('Normaali', 'Normaali')], default='Normaali', max_length=512)),
                ('etunimi', models.CharField(blank=True, max_length=512)),
                ('sukunimi', models.CharField(blank=True, max_length=512)),
                ('teon_kuvaus', models.CharField(blank=True, max_length=512)),
                ('toimenpidepyynto', models.CharField(blank=True, max_length=512)),
                ('salasana', models.CharField(blank=True, max_length=512)),
                ('pin_koodi', models.CharField(blank=True, max_length=512)),
                ('kirjauspvm', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asianosaisuus', models.CharField(choices=[('Asianomistaja', 'AO'), ('Rikoksesta epäilty', 'RE'), ('Todistaja', 'Todistaja'), ('Muu', 'Muu')], default='Rikoksesta epäilty', max_length=512)),
                ('paattaja', models.CharField(max_length=512, null=True)),
                ('paatos_pvm', models.DateField(default=django.utils.timezone.now, verbose_name=django.forms.widgets.SelectDateWidget)),
            ],
        ),
        migrations.CreateModel(
            name='JuttuStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=512)),
                ('on_aktiivinen', models.BooleanField(default=True)),
                ('valmis_status', models.BooleanField(default=False)),
                ('aloittamatta_status', models.BooleanField(default=False)),
                ('odottaa_status', models.BooleanField(default=False)),
                ('aloitettu_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Muistiinpanot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muistiinpano', models.TextField()),
                ('kirjauspvm', models.DateField(default=django.utils.timezone.now, verbose_name=django.forms.widgets.SelectDateWidget)),
                ('raporttiin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nimikkeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TutkintaRyhma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutkintaryhma', models.CharField(blank=True, max_length=512)),
                ('on_aktiivinen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salasanat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juttu_salasana', models.CharField(blank=True, max_length=512)),
                ('juttu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juttu_salasanat', to='juttu.Juttu')),
            ],
        ),
        migrations.CreateModel(
            name='Poikkeamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poikkeama', models.TextField()),
                ('kirjauspvm', models.DateField(default=django.utils.timezone.now, verbose_name=django.forms.widgets.SelectDateWidget)),
                ('raporttiin', models.BooleanField(default=False)),
                ('it_tutkija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poikkeamat', to=settings.AUTH_USER_MODEL, verbose_name='IT-Tutkija')),
                ('juttu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juttu_poikkeamat', to='juttu.Juttu')),
            ],
        ),
    ]
