# Generated by Django 3.0.3 on 2020-11-25 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laite', '0001_initial'),
        ('juttu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poikkeamat',
            name='laite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laite_poikkeamat', to='laite.Laite'),
        ),
        migrations.AddField(
            model_name='muistiinpanot',
            name='it_tutkija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_muistiinpano', to=settings.AUTH_USER_MODEL, verbose_name='IT-Tutkija'),
        ),
        migrations.AddField(
            model_name='muistiinpanot',
            name='juttu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juttu_notes', to='juttu.Juttu'),
        ),
        migrations.AddField(
            model_name='juttu',
            name='juttu_status',
            field=models.ForeignKey(default=1, limit_choices_to={'on_aktiivinen': True}, on_delete=django.db.models.deletion.CASCADE, related_name='jutun_status', to='juttu.JuttuStatus'),
        ),
        migrations.AddField(
            model_name='juttu',
            name='ryhma',
            field=models.ForeignKey(limit_choices_to={'on_aktiivinen': True}, on_delete=django.db.models.deletion.CASCADE, related_name='jutun_ryhma', to='juttu.TutkintaRyhma'),
        ),
        migrations.AddField(
            model_name='juttu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_juttus', to=settings.AUTH_USER_MODEL),
        ),
    ]
